#!/bin/bash

echo Running checkBenchmarkPicoc.sh ...
./checkBenchmarkPicoc.sh > results-picoc.txt
echo Running generateTokenCounts.sh ...
./generateTokenCounts.sh > results-tokens.csv
echo Running generateParameterCounts.sh ...
./generateParameterCounts.sh > results-functionparams.csv
echo Running generateDynamicParameterCounts.sh ...
./generateDynamicParameterCounts.sh > results-functionparamsdynamic.csv
echo Running generateWatermarks.sh ...
./generateWatermarks.sh > results-watermarks.csv
echo Running generateAssignmentCounts.sh ...
./generateAssignmentCounts.sh > results-assignments.csv
